// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: menu/menu.proto

package menu

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// MenuInfo メニューのデータ
type MenuInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title             string      `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`                                                      // タイトル
	Desc              string      `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`                                                        // 説明
	Path              string      `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`                                                        // 遷移先
	ChildMenuInfoList []*MenuInfo `protobuf:"bytes,4,rep,name=child_menu_info_list,json=childMenuInfoList,proto3" json:"child_menu_info_list,omitempty"` // 関連付けされた子Menu
}

func (x *MenuInfo) Reset() {
	*x = MenuInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_menu_menu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MenuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuInfo) ProtoMessage() {}

func (x *MenuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_menu_menu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuInfo.ProtoReflect.Descriptor instead.
func (*MenuInfo) Descriptor() ([]byte, []int) {
	return file_menu_menu_proto_rawDescGZIP(), []int{0}
}

func (x *MenuInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MenuInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *MenuInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MenuInfo) GetChildMenuInfoList() []*MenuInfo {
	if x != nil {
		return x.ChildMenuInfoList
	}
	return nil
}

var File_menu_menu_proto protoreflect.FileDescriptor

var file_menu_menu_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x65, 0x6e, 0x75, 0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6d, 0x65, 0x6e, 0x75, 0x22, 0x89, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x6e, 0x75,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65,
	0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x3f, 0x0a, 0x14, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x5f, 0x6d, 0x65, 0x6e, 0x75,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x11, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x33, 0x5a, 0x31, 0x61, 0x6c, 0x6d, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x61, 0x70, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_menu_menu_proto_rawDescOnce sync.Once
	file_menu_menu_proto_rawDescData = file_menu_menu_proto_rawDesc
)

func file_menu_menu_proto_rawDescGZIP() []byte {
	file_menu_menu_proto_rawDescOnce.Do(func() {
		file_menu_menu_proto_rawDescData = protoimpl.X.CompressGZIP(file_menu_menu_proto_rawDescData)
	})
	return file_menu_menu_proto_rawDescData
}

var file_menu_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_menu_menu_proto_goTypes = []interface{}{
	(*MenuInfo)(nil), // 0: menu.MenuInfo
}
var file_menu_menu_proto_depIdxs = []int32{
	0, // 0: menu.MenuInfo.child_menu_info_list:type_name -> menu.MenuInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_menu_menu_proto_init() }
func file_menu_menu_proto_init() {
	if File_menu_menu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_menu_menu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MenuInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_menu_menu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_menu_menu_proto_goTypes,
		DependencyIndexes: file_menu_menu_proto_depIdxs,
		MessageInfos:      file_menu_menu_proto_msgTypes,
	}.Build()
	File_menu_menu_proto = out.File
	file_menu_menu_proto_rawDesc = nil
	file_menu_menu_proto_goTypes = nil
	file_menu_menu_proto_depIdxs = nil
}
