// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.13.0
// source: member/invite/invite.proto

package invite

import (
	common "alma-server/ap/src/infrastructure/grpc/proto/common"
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PageHTMLReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventName            string              `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	MemberInviteInfoList []*MemberInviteInfo `protobuf:"bytes,2,rep,name=member_invite_info_list,json=memberInviteInfoList,proto3" json:"member_invite_info_list,omitempty"`
}

func (x *PageHTMLReply) Reset() {
	*x = PageHTMLReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_invite_invite_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageHTMLReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageHTMLReply) ProtoMessage() {}

func (x *PageHTMLReply) ProtoReflect() protoreflect.Message {
	mi := &file_member_invite_invite_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageHTMLReply.ProtoReflect.Descriptor instead.
func (*PageHTMLReply) Descriptor() ([]byte, []int) {
	return file_member_invite_invite_proto_rawDescGZIP(), []int{0}
}

func (x *PageHTMLReply) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *PageHTMLReply) GetMemberInviteInfoList() []*MemberInviteInfo {
	if x != nil {
		return x.MemberInviteInfoList
	}
	return nil
}

type MemberInviteInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email     string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Auth      string                 `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *MemberInviteInfo) Reset() {
	*x = MemberInviteInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_invite_invite_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberInviteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInviteInfo) ProtoMessage() {}

func (x *MemberInviteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_member_invite_invite_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInviteInfo.ProtoReflect.Descriptor instead.
func (*MemberInviteInfo) Descriptor() ([]byte, []int) {
	return file_member_invite_invite_proto_rawDescGZIP(), []int{1}
}

func (x *MemberInviteInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MemberInviteInfo) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *MemberInviteInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_member_invite_invite_proto protoreflect.FileDescriptor

var file_member_invite_invite_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2f,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x69, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7f, 0x0a, 0x0d, 0x50, 0x61,
	0x67, 0x65, 0x48, 0x54, 0x4d, 0x4c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x4f, 0x0a, 0x17, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x14, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x77, 0x0a, 0x10, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x32, 0x47, 0x0a, 0x0c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x48, 0x54, 0x4d, 0x4c,
	0x12, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e,
	0x50, 0x61, 0x67, 0x65, 0x48, 0x54, 0x4d, 0x4c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x3c, 0x5a,
	0x3a, 0x61, 0x6c, 0x6d, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x2f,
	0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_member_invite_invite_proto_rawDescOnce sync.Once
	file_member_invite_invite_proto_rawDescData = file_member_invite_invite_proto_rawDesc
)

func file_member_invite_invite_proto_rawDescGZIP() []byte {
	file_member_invite_invite_proto_rawDescOnce.Do(func() {
		file_member_invite_invite_proto_rawDescData = protoimpl.X.CompressGZIP(file_member_invite_invite_proto_rawDescData)
	})
	return file_member_invite_invite_proto_rawDescData
}

var file_member_invite_invite_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_member_invite_invite_proto_goTypes = []interface{}{
	(*PageHTMLReply)(nil),         // 0: invite.PageHTMLReply
	(*MemberInviteInfo)(nil),      // 1: invite.MemberInviteInfo
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*common.EventRequest)(nil),   // 3: common.EventRequest
}
var file_member_invite_invite_proto_depIdxs = []int32{
	1, // 0: invite.PageHTMLReply.member_invite_info_list:type_name -> invite.MemberInviteInfo
	2, // 1: invite.MemberInviteInfo.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: invite.MemberInvite.PageHTML:input_type -> common.EventRequest
	0, // 3: invite.MemberInvite.PageHTML:output_type -> invite.PageHTMLReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_member_invite_invite_proto_init() }
func file_member_invite_invite_proto_init() {
	if File_member_invite_invite_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_member_invite_invite_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageHTMLReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_invite_invite_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberInviteInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_member_invite_invite_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_member_invite_invite_proto_goTypes,
		DependencyIndexes: file_member_invite_invite_proto_depIdxs,
		MessageInfos:      file_member_invite_invite_proto_msgTypes,
	}.Build()
	File_member_invite_invite_proto = out.File
	file_member_invite_invite_proto_rawDesc = nil
	file_member_invite_invite_proto_goTypes = nil
	file_member_invite_invite_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MemberInviteClient is the client API for MemberInvite service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MemberInviteClient interface {
	// PageHTML
	PageHTML(ctx context.Context, in *common.EventRequest, opts ...grpc.CallOption) (*PageHTMLReply, error)
}

type memberInviteClient struct {
	cc grpc.ClientConnInterface
}

func NewMemberInviteClient(cc grpc.ClientConnInterface) MemberInviteClient {
	return &memberInviteClient{cc}
}

func (c *memberInviteClient) PageHTML(ctx context.Context, in *common.EventRequest, opts ...grpc.CallOption) (*PageHTMLReply, error) {
	out := new(PageHTMLReply)
	err := c.cc.Invoke(ctx, "/invite.MemberInvite/PageHTML", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemberInviteServer is the server API for MemberInvite service.
type MemberInviteServer interface {
	// PageHTML
	PageHTML(context.Context, *common.EventRequest) (*PageHTMLReply, error)
}

// UnimplementedMemberInviteServer can be embedded to have forward compatible implementations.
type UnimplementedMemberInviteServer struct {
}

func (*UnimplementedMemberInviteServer) PageHTML(context.Context, *common.EventRequest) (*PageHTMLReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PageHTML not implemented")
}

func RegisterMemberInviteServer(s *grpc.Server, srv MemberInviteServer) {
	s.RegisterService(&_MemberInvite_serviceDesc, srv)
}

func _MemberInvite_PageHTML_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberInviteServer).PageHTML(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/invite.MemberInvite/PageHTML",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberInviteServer).PageHTML(ctx, req.(*common.EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MemberInvite_serviceDesc = grpc.ServiceDesc{
	ServiceName: "invite.MemberInvite",
	HandlerType: (*MemberInviteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PageHTML",
			Handler:    _MemberInvite_PageHTML_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "member/invite/invite.proto",
}
