// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.13.0
// source: sales/sales.proto

package sales

import (
	common "alma-server/ap/src/infrastructure/grpc/proto/common"
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var File_sales_sales_proto protoreflect.FileDescriptor

var file_sales_sales_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x2f, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32,
	0x3a, 0x0a, 0x05, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65,
	0x48, 0x54, 0x4d, 0x4c, 0x12, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x34, 0x5a, 0x32, 0x61,
	0x6c, 0x6d, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x2f, 0x73, 0x72,
	0x63, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x61, 0x6c, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_sales_sales_proto_goTypes = []interface{}{
	(*common.EventRequest)(nil), // 0: common.EventRequest
	(*common.Empty)(nil),        // 1: common.Empty
}
var file_sales_sales_proto_depIdxs = []int32{
	0, // 0: sales.Sales.PageHTML:input_type -> common.EventRequest
	1, // 1: sales.Sales.PageHTML:output_type -> common.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sales_sales_proto_init() }
func file_sales_sales_proto_init() {
	if File_sales_sales_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sales_sales_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sales_sales_proto_goTypes,
		DependencyIndexes: file_sales_sales_proto_depIdxs,
	}.Build()
	File_sales_sales_proto = out.File
	file_sales_sales_proto_rawDesc = nil
	file_sales_sales_proto_goTypes = nil
	file_sales_sales_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SalesClient is the client API for Sales service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SalesClient interface {
	// PageHTML 売上のトップ画面
	PageHTML(ctx context.Context, in *common.EventRequest, opts ...grpc.CallOption) (*common.Empty, error)
}

type salesClient struct {
	cc grpc.ClientConnInterface
}

func NewSalesClient(cc grpc.ClientConnInterface) SalesClient {
	return &salesClient{cc}
}

func (c *salesClient) PageHTML(ctx context.Context, in *common.EventRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/sales.Sales/PageHTML", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SalesServer is the server API for Sales service.
type SalesServer interface {
	// PageHTML 売上のトップ画面
	PageHTML(context.Context, *common.EventRequest) (*common.Empty, error)
}

// UnimplementedSalesServer can be embedded to have forward compatible implementations.
type UnimplementedSalesServer struct {
}

func (*UnimplementedSalesServer) PageHTML(context.Context, *common.EventRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PageHTML not implemented")
}

func RegisterSalesServer(s *grpc.Server, srv SalesServer) {
	s.RegisterService(&_Sales_serviceDesc, srv)
}

func _Sales_PageHTML_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SalesServer).PageHTML(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sales.Sales/PageHTML",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SalesServer).PageHTML(ctx, req.(*common.EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sales_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sales.Sales",
	HandlerType: (*SalesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PageHTML",
			Handler:    _Sales_PageHTML_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sales/sales.proto",
}
