// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.13.0
// source: reserve/reserve.proto

package reserve

import (
	common "alma-server/ap/src/infrastructure/grpc/proto/common"
	ticket "alma-server/ap/src/infrastructure/grpc/proto/ticket"
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventName       string         `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventId         string         `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ReserveInfoList []*ReserveInfo `protobuf:"bytes,3,rep,name=reserve_info_list,json=reserveInfoList,proto3" json:"reserve_info_list,omitempty"`
}

func (x *PageReply) Reset() {
	*x = PageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reserve_reserve_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageReply) ProtoMessage() {}

func (x *PageReply) ProtoReflect() protoreflect.Message {
	mi := &file_reserve_reserve_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageReply.ProtoReflect.Descriptor instead.
func (*PageReply) Descriptor() ([]byte, []int) {
	return file_reserve_reserve_proto_rawDescGZIP(), []int{0}
}

func (x *PageReply) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *PageReply) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PageReply) GetReserveInfoList() []*ReserveInfo {
	if x != nil {
		return x.ReserveInfoList
	}
	return nil
}

type CreatePageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId           string                  `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventName         string                  `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	TicketInfoList    []*ticket.TicketInfo    `protobuf:"bytes,3,rep,name=ticket_info_list,json=ticketInfoList,proto3" json:"ticket_info_list,omitempty"`
	TicketPayTypeList []*ticket.TicketPayType `protobuf:"bytes,4,rep,name=ticket_pay_type_list,json=ticketPayTypeList,proto3" json:"ticket_pay_type_list,omitempty"`
}

func (x *CreatePageReply) Reset() {
	*x = CreatePageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reserve_reserve_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePageReply) ProtoMessage() {}

func (x *CreatePageReply) ProtoReflect() protoreflect.Message {
	mi := &file_reserve_reserve_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePageReply.ProtoReflect.Descriptor instead.
func (*CreatePageReply) Descriptor() ([]byte, []int) {
	return file_reserve_reserve_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePageReply) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreatePageReply) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *CreatePageReply) GetTicketInfoList() []*ticket.TicketInfo {
	if x != nil {
		return x.TicketInfoList
	}
	return nil
}

func (x *CreatePageReply) GetTicketPayTypeList() []*ticket.TicketPayType {
	if x != nil {
		return x.TicketPayTypeList
	}
	return nil
}

type CreateReserveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId  string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TicketId string `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	// google.protobuf.Timestamp event_start_date = 3;
	ScheduleId   string `protobuf:"bytes,3,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	TicketNum    int32  `protobuf:"varint,4,opt,name=ticket_num,json=ticketNum,proto3" json:"ticket_num,omitempty"`
	Desc         string `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	Name         string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	NameFurigana string `protobuf:"bytes,7,opt,name=name_furigana,json=nameFurigana,proto3" json:"name_furigana,omitempty"`
	Email        string `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	PayTypeId    string `protobuf:"bytes,9,opt,name=pay_type_id,json=payTypeId,proto3" json:"pay_type_id,omitempty"`
}

func (x *CreateReserveRequest) Reset() {
	*x = CreateReserveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reserve_reserve_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReserveRequest) ProtoMessage() {}

func (x *CreateReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reserve_reserve_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReserveRequest.ProtoReflect.Descriptor instead.
func (*CreateReserveRequest) Descriptor() ([]byte, []int) {
	return file_reserve_reserve_proto_rawDescGZIP(), []int{2}
}

func (x *CreateReserveRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateReserveRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *CreateReserveRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *CreateReserveRequest) GetTicketNum() int32 {
	if x != nil {
		return x.TicketNum
	}
	return 0
}

func (x *CreateReserveRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateReserveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateReserveRequest) GetNameFurigana() string {
	if x != nil {
		return x.NameFurigana
	}
	return ""
}

func (x *CreateReserveRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateReserveRequest) GetPayTypeId() string {
	if x != nil {
		return x.PayTypeId
	}
	return ""
}

// ReserveInfo 予約の要素
type ReserveInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReserveId      string                 `protobuf:"bytes,1,opt,name=reserve_id,json=reserveId,proto3" json:"reserve_id,omitempty"`                  // uniqueな予約ID
	Seq            uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`                                              // そのEvent内でのuniqueな番号
	TicketName     string                 `protobuf:"bytes,3,opt,name=ticket_name,json=ticketName,proto3" json:"ticket_name,omitempty"`               // 予約したチケット名
	TicketNum      int32                  `protobuf:"varint,4,opt,name=ticket_num,json=ticketNum,proto3" json:"ticket_num,omitempty"`                 // チケット枚数
	TicketKindName string                 `protobuf:"bytes,5,opt,name=ticket_kind_name,json=ticketKindName,proto3" json:"ticket_kind_name,omitempty"` // チケット種類名
	Name           string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	NameFurigana   string                 `protobuf:"bytes,7,opt,name=name_furigana,json=nameFurigana,proto3" json:"name_furigana,omitempty"`
	Email          string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`                                            // email
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                   // 作成時間
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                  // 更新時間
	CustomorId     string                 `protobuf:"bytes,11,opt,name=customor_id,json=customorId,proto3" json:"customor_id,omitempty"`               // 顧客ID
	EventStartTime *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=event_start_time,json=eventStartTime,proto3" json:"event_start_time,omitempty"` // イベント開始時間
	PayTypeName    string                 `protobuf:"bytes,13,opt,name=pay_type_name,json=payTypeName,proto3" json:"pay_type_name,omitempty"`          // 支払い方法の種類
}

func (x *ReserveInfo) Reset() {
	*x = ReserveInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reserve_reserve_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReserveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveInfo) ProtoMessage() {}

func (x *ReserveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_reserve_reserve_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveInfo.ProtoReflect.Descriptor instead.
func (*ReserveInfo) Descriptor() ([]byte, []int) {
	return file_reserve_reserve_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveInfo) GetReserveId() string {
	if x != nil {
		return x.ReserveId
	}
	return ""
}

func (x *ReserveInfo) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ReserveInfo) GetTicketName() string {
	if x != nil {
		return x.TicketName
	}
	return ""
}

func (x *ReserveInfo) GetTicketNum() int32 {
	if x != nil {
		return x.TicketNum
	}
	return 0
}

func (x *ReserveInfo) GetTicketKindName() string {
	if x != nil {
		return x.TicketKindName
	}
	return ""
}

func (x *ReserveInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReserveInfo) GetNameFurigana() string {
	if x != nil {
		return x.NameFurigana
	}
	return ""
}

func (x *ReserveInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ReserveInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReserveInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ReserveInfo) GetCustomorId() string {
	if x != nil {
		return x.CustomorId
	}
	return ""
}

func (x *ReserveInfo) GetEventStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventStartTime
	}
	return nil
}

func (x *ReserveInfo) GetPayTypeName() string {
	if x != nil {
		return x.PayTypeName
	}
	return ""
}

var File_reserve_reserve_proto protoreflect.FileDescriptor

var file_reserve_reserve_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x74, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x01, 0x0a, 0x09,
	0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x40, 0x0a, 0x11, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xd1, 0x01, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x10, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x0e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x46, 0x0a, 0x14, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x70, 0x61, 0x79, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x50,
	0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x11, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x50, 0x61,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x91, 0x02, 0x0a, 0x14, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65,
	0x73, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x66, 0x75, 0x72, 0x69, 0x67,
	0x61, 0x6e, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x61, 0x6d, 0x65, 0x46,
	0x75, 0x72, 0x69, 0x67, 0x61, 0x6e, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1e, 0x0a,
	0x0b, 0x70, 0x61, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x22, 0xf8, 0x03,
	0x0a, 0x0b, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x1f,
	0x0a, 0x0b, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x28,
	0x0a, 0x10, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x4b, 0x69, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x66, 0x75, 0x72, 0x69, 0x67, 0x61, 0x6e, 0x61, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x61, 0x6d, 0x65, 0x46, 0x75, 0x72, 0x69, 0x67, 0x61, 0x6e,
	0x61, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x44,
	0x0a, 0x10, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x70, 0x61, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0xc6, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x48, 0x54, 0x4d, 0x4c,
	0x12, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x67, 0x65, 0x48, 0x54, 0x4d, 0x4c, 0x12, 0x14,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x3f, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x12, 0x1d, 0x2e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x42, 0x36, 0x5a, 0x34, 0x61, 0x6c, 0x6d, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x61, 0x70, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_reserve_reserve_proto_rawDescOnce sync.Once
	file_reserve_reserve_proto_rawDescData = file_reserve_reserve_proto_rawDesc
)

func file_reserve_reserve_proto_rawDescGZIP() []byte {
	file_reserve_reserve_proto_rawDescOnce.Do(func() {
		file_reserve_reserve_proto_rawDescData = protoimpl.X.CompressGZIP(file_reserve_reserve_proto_rawDescData)
	})
	return file_reserve_reserve_proto_rawDescData
}

var file_reserve_reserve_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_reserve_reserve_proto_goTypes = []interface{}{
	(*PageReply)(nil),             // 0: reserve.PageReply
	(*CreatePageReply)(nil),       // 1: reserve.CreatePageReply
	(*CreateReserveRequest)(nil),  // 2: reserve.CreateReserveRequest
	(*ReserveInfo)(nil),           // 3: reserve.ReserveInfo
	(*ticket.TicketInfo)(nil),     // 4: ticket.TicketInfo
	(*ticket.TicketPayType)(nil),  // 5: ticket.TicketPayType
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*common.EventRequest)(nil),   // 7: common.EventRequest
	(*common.Empty)(nil),          // 8: common.Empty
}
var file_reserve_reserve_proto_depIdxs = []int32{
	3, // 0: reserve.PageReply.reserve_info_list:type_name -> reserve.ReserveInfo
	4, // 1: reserve.CreatePageReply.ticket_info_list:type_name -> ticket.TicketInfo
	5, // 2: reserve.CreatePageReply.ticket_pay_type_list:type_name -> ticket.TicketPayType
	6, // 3: reserve.ReserveInfo.created_at:type_name -> google.protobuf.Timestamp
	6, // 4: reserve.ReserveInfo.updated_at:type_name -> google.protobuf.Timestamp
	6, // 5: reserve.ReserveInfo.event_start_time:type_name -> google.protobuf.Timestamp
	7, // 6: reserve.Reserve.PageHTML:input_type -> common.EventRequest
	7, // 7: reserve.Reserve.CreatePageHTML:input_type -> common.EventRequest
	2, // 8: reserve.Reserve.CreateReserve:input_type -> reserve.CreateReserveRequest
	0, // 9: reserve.Reserve.PageHTML:output_type -> reserve.PageReply
	1, // 10: reserve.Reserve.CreatePageHTML:output_type -> reserve.CreatePageReply
	8, // 11: reserve.Reserve.CreateReserve:output_type -> common.Empty
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_reserve_reserve_proto_init() }
func file_reserve_reserve_proto_init() {
	if File_reserve_reserve_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reserve_reserve_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reserve_reserve_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reserve_reserve_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReserveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reserve_reserve_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReserveInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reserve_reserve_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reserve_reserve_proto_goTypes,
		DependencyIndexes: file_reserve_reserve_proto_depIdxs,
		MessageInfos:      file_reserve_reserve_proto_msgTypes,
	}.Build()
	File_reserve_reserve_proto = out.File
	file_reserve_reserve_proto_rawDesc = nil
	file_reserve_reserve_proto_goTypes = nil
	file_reserve_reserve_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReserveClient is the client API for Reserve service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReserveClient interface {
	// PageHTML 予約のトップ画面
	PageHTML(ctx context.Context, in *common.EventRequest, opts ...grpc.CallOption) (*PageReply, error)
	// CreatePageHTML 予約の作成画面
	CreatePageHTML(ctx context.Context, in *common.EventRequest, opts ...grpc.CallOption) (*CreatePageReply, error)
	// CreateReserve 予約の作成
	CreateReserve(ctx context.Context, in *CreateReserveRequest, opts ...grpc.CallOption) (*common.Empty, error)
}

type reserveClient struct {
	cc grpc.ClientConnInterface
}

func NewReserveClient(cc grpc.ClientConnInterface) ReserveClient {
	return &reserveClient{cc}
}

func (c *reserveClient) PageHTML(ctx context.Context, in *common.EventRequest, opts ...grpc.CallOption) (*PageReply, error) {
	out := new(PageReply)
	err := c.cc.Invoke(ctx, "/reserve.Reserve/PageHTML", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reserveClient) CreatePageHTML(ctx context.Context, in *common.EventRequest, opts ...grpc.CallOption) (*CreatePageReply, error) {
	out := new(CreatePageReply)
	err := c.cc.Invoke(ctx, "/reserve.Reserve/CreatePageHTML", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reserveClient) CreateReserve(ctx context.Context, in *CreateReserveRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/reserve.Reserve/CreateReserve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReserveServer is the server API for Reserve service.
type ReserveServer interface {
	// PageHTML 予約のトップ画面
	PageHTML(context.Context, *common.EventRequest) (*PageReply, error)
	// CreatePageHTML 予約の作成画面
	CreatePageHTML(context.Context, *common.EventRequest) (*CreatePageReply, error)
	// CreateReserve 予約の作成
	CreateReserve(context.Context, *CreateReserveRequest) (*common.Empty, error)
}

// UnimplementedReserveServer can be embedded to have forward compatible implementations.
type UnimplementedReserveServer struct {
}

func (*UnimplementedReserveServer) PageHTML(context.Context, *common.EventRequest) (*PageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PageHTML not implemented")
}
func (*UnimplementedReserveServer) CreatePageHTML(context.Context, *common.EventRequest) (*CreatePageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePageHTML not implemented")
}
func (*UnimplementedReserveServer) CreateReserve(context.Context, *CreateReserveRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReserve not implemented")
}

func RegisterReserveServer(s *grpc.Server, srv ReserveServer) {
	s.RegisterService(&_Reserve_serviceDesc, srv)
}

func _Reserve_PageHTML_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReserveServer).PageHTML(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reserve.Reserve/PageHTML",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReserveServer).PageHTML(ctx, req.(*common.EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reserve_CreatePageHTML_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReserveServer).CreatePageHTML(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reserve.Reserve/CreatePageHTML",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReserveServer).CreatePageHTML(ctx, req.(*common.EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reserve_CreateReserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReserveServer).CreateReserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reserve.Reserve/CreateReserve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReserveServer).CreateReserve(ctx, req.(*CreateReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reserve_serviceDesc = grpc.ServiceDesc{
	ServiceName: "reserve.Reserve",
	HandlerType: (*ReserveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PageHTML",
			Handler:    _Reserve_PageHTML_Handler,
		},
		{
			MethodName: "CreatePageHTML",
			Handler:    _Reserve_CreatePageHTML_Handler,
		},
		{
			MethodName: "CreateReserve",
			Handler:    _Reserve_CreateReserve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reserve/reserve.proto",
}
